# Generated by Django 4.1.3 on 2022-12-02 13:21

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('icon', models.CharField(choices=[('lni-laptop-phone', 'Pc/Celular'), ('lni-database', 'Banco de dados'), ('lni-leaf', 'Folha'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Multicamada'), ('lni-rocket', 'Foguete')], max_length=18, verbose_name='Icone')),
                ('name', models.CharField(max_length=50, verbose_name='Recurso')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('icone', models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico')], max_length=12, verbose_name='Icone')),
                ('nome', models.CharField(max_length=100, verbose_name='Serviço')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('biografia', models.TextField(max_length=200, verbose_name='Biografia')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'height': 300, 'width': 300}}, verbose_name='Foto')),
                ('facebook', models.CharField(default='#', max_length=200, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=200, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=200, verbose_name='Instagram')),
                ('linkedin', models.CharField(default='#', max_length=200, verbose_name='Linkedin')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('comentario', models.TextField(max_length=120, verbose_name='Comentário')),
                ('estrelas', models.IntegerField(choices=[(2, '★★'), (3, '★★★'), (5, '★★★★★'), (1, '★'), (4, '★★★★')], verbose_name='Estrelas')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'height': 75, 'width': 75}}, verbose_name='Foto')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
