# Generated by Django 4.1.3 on 2022-11-17 05:27

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('servico', models.CharField(max_length=100, verbose_name='Serviço')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuários'), ('lni-rocket', 'Foguete'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('Biografia', models.TextField(max_length=200, verbose_name='Biografia')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'height': 480, 'width': 480}}, verbose_name='Foto')),
                ('facebook', models.CharField(default='#', max_length=200, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=200, verbose_name='twitter')),
                ('instagram', models.CharField(default='#', max_length=200, verbose_name='instagram')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
