# Generated by Django 4.1.3 on 2022-11-17 13:24

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'height': 300, 'width': 300}}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-layers', 'Design'), ('lni-users', 'Usuários'), ('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
