# Generated by Django 4.1.3 on 2022-12-07 12:11

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='estrelas',
            field=models.IntegerField(choices=[(5, '★★★★★'), (3, '★★★'), (1, '★'), (4, '★★★★'), (2, '★★')], verbose_name='Estrelas'),
        ),
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(choices=[('lni-laptop-phone', 'Pc/Celular'), ('lni-layers', 'Multicamada'), ('lni-cog', 'Engrenagem'), ('lni-database', 'Banco de dados'), ('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha')], max_length=18, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'height': 300, 'width': 300}}, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários')], max_length=12, verbose_name='Icone'),
        ),
    ]
