# Generated by Django 4.1.3 on 2022-11-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_biografia_funcionario_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('icon', models.CharField(choices=[('lni-leaf', 'Folha'), ('lni-layers', 'Multicamada'), ('lni-database', 'Banco de dados'), ('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Pc/Celular'), ('lni-rocket', 'Foguete')], max_length=18, verbose_name='Icone')),
                ('name', models.CharField(max_length=50, verbose_name='Recurso')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'ServiSo',
                'verbose_name_plural': 'ServoSoS',
            },
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='servico',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
    ]
