# Generated by Django 4.1.3 on 2022-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_features_icon_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-leaf', 'Folha'), ('lni-layers', 'Multicamada'), ('lni-cog', 'Engrenagem'), ('lni-laptop-phone', 'Pc/Celular'), ('lni-database', 'Banco de dados')], max_length=18, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-users', 'Usuários'), ('lni-layers', 'Design'), ('lni-stats-up', 'Gráfico'), ('lni-mobile', 'Mobile')], max_length=12, verbose_name='Icone'),
        ),
    ]
