# Generated by Django 4.1.3 on 2022-12-02 12:24

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_features_icon_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(choices=[('lni-database', 'Banco de dados'), ('lni-leaf', 'Folha'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Multicamada'), ('lni-laptop-phone', 'Pc/Celular'), ('lni-cog', 'Engrenagem')], max_length=18, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-users', 'Usuários'), ('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Data Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('comentario', models.TextField(max_length=120, verbose_name='Comentário')),
                ('estrelas', models.CharField(choices=[('4', '★★★★'), ('1', '★'), ('2', '★★'), ('5', '★★★★★'), ('3', '★★★')], max_length=5, verbose_name='Estrelas')),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='equipe', variations={'thumb': {'height': 75, 'width': 75}}, verbose_name='Foto')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
