# Generated by Django 4.1.3 on 2022-12-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_features_icon_alter_servico_icone_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='estrelas',
            field=models.IntegerField(choices=[(1, '★'), (4, '★★★★'), (2, '★★'), (5, '★★★★★'), (3, '★★★')], max_length=5, verbose_name='Estrelas'),
        ),
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.CharField(choices=[('lni-layers', 'Multicamada'), ('lni-leaf', 'Folha'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-database', 'Banco de dados'), ('lni-laptop-phone', 'Pc/Celular')], max_length=18, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-users', 'Usuários')], max_length=12, verbose_name='Icone'),
        ),
    ]
